---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/pets":
    get:
      summary: listPets pet
      tags:
      - Pets
      parameters:
      - name: limit
        in: query
        description: Limit for the number of pets
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                - code
                - message
    post:
      summary: createPets pet
      responses:
        '200':
          description: successful
  "/pets/{petId}":
    parameters:
    - name: petId
      in: path
      description: petId
      required: true
      schema:
        type: string
    get:
      summary: show pet
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
